name: Node.js CI with OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache OWASP Dependency-Check
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.dependency-check
        key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-

    - name: Download OWASP Dependency-Check
      run: |
        if [ ! -f ~/.dependency-check/dependency-check.sh ]; then
          wget -O dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
          unzip dependency-check.zip -d ~/.dependency-check
        fi

    - name: Install Node.js dependencies
      run: npm install

    - name: Run OWASP Dependency-Check
      run: |
        ~/.dependency-check/bin/dependency-check.sh --enableExperimental --format HTML --out . --scan .
      continue-on-error: true

    - name: Archive Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-report
        path: dependency-check-report.html
